# Generated by Django 4.2.10 on 2024-02-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo1",
                    models.ImageField(
                        blank=True, null=True, upload_to="comment/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo2",
                    models.ImageField(
                        blank=True, null=True, upload_to="comment/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo3",
                    models.ImageField(
                        blank=True, null=True, upload_to="comment/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo4",
                    models.ImageField(
                        blank=True, null=True, upload_to="comment/%Y/%m/%d/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("body", models.TextField()),
            ],
        ),
    ]
