# Generated by Django 4.2.8 on 2024-02-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_initial"),
        ("user_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="products",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
        ),
    ]
